# Generated by Django 2.2.10 on 2021-02-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import surveys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Publication date')),
                ('end_date', models.DateField(blank=True, default=surveys.models.in_duration_day, verbose_name='Expiration date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer_type', models.CharField(choices=[('text', 'text'), ('select-single', 'select single'), ('select-multiple', 'select multiple')], default='text', max_length=200, verbose_name='Type')),
                ('answer_choices', models.TextField(blank=True, help_text='The choices field is only used if the question type is "select-single" or "select multiple" provide a comma-separated list of options for this question.', null=True, verbose_name='Choices')),
                ('author', models.ForeignKey(on_delete=models.SET(surveys.models.get_sentinel_user), related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-survey',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ('-question',),
            },
        ),
    ]
